import http from 'http'
import https from 'https'
import axios, {AxiosResponse, AxiosRequestConfig, CancelTokenStatic} from 'axios'
import { Message, MessageBox} from 'element-ui'
import qs from  'qs'
import { UserModule } from '@/store/modules/user'
